language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements/ci.txt
env:
  - NM_LAUNCH_API_SETTINGS=nm_launch_api.config.local
# command to run tests
script:
  - python setup.py test